<Project Sdk="Fahrenheit.Sdk/1.0.0-alpha08">

	<!-- ASSEMBLY BASIC PROPERTIES -->
    <PropertyGroup>
	    <Version>0.5.1-alpha</Version>
    </PropertyGroup>

	<!-- ASSEMBLY ADDITIONAL PROPERTIES -->
	<PropertyGroup>
		<AssemblyName>archipelago-ffx</AssemblyName>
		<AssemblyTitle>Fahrenheit Archipelago Mod for Final Fantasy X</AssemblyTitle>
		<Product>Fahrenheit Archipelago Mod for Final Fantasy X</Product>
		<RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
		<DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
	</PropertyGroup>

	<!-- SHARED FILE LINKS -->
	<ItemGroup>
		<None Include="$(SolutionDir).editorconfig" Link=".editorconfig" />
	</ItemGroup>

    <!-- PACKAGE REFERENCES -->
	<ItemGroup>
		<PackageReference Include="Archipelago.MultiClient.Net" Version="6.7.0" />
	</ItemGroup>

	<!-- BUILD EVENTS -->
    <Target Name="ReplaceProperties" AfterTargets="Publish">
        <PropertyGroup>
            <WorkingDirectory>$(PublishDir)</WorkingDirectory>
            <File>archipelago-ffx.manifest.json</File>
        </PropertyGroup>

        <WriteLinesToFile
                File="$(WorkingDirectory)/$(File)"
                Lines="$([System.IO.File]::ReadAllText($(WorkingDirectory)/$(File)).Replace('{Version}','$(Version)'))"
                Overwrite="true"
                Encoding="Unicode" />
    </Target>

</Project>
